import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell } from "@/components/AppShell";
import { AIPanel } from "@/components/AIPanel";
import { officerNav } from "@/lib/nav";
import { officerUser } from "@/lib/mock";
import { Badge, SectionTitle, KPITile } from "@/components/ui-bits";
import { Sparkles, ArrowRight, FileText, Download } from "lucide-react";

export const Route = createFileRoute("/officer/research")({
  head: () => ({ meta: [{ title: "Research Hub — MYFutureJobs" }] }),
  component: Page,
});

const skillsRadar = [
  { skill: "PLC", you: 60, target: 90 },
  { skill: "Robotics", you: 45, target: 85 },
  { skill: "QA", you: 70, target: 75 },
  { skill: "CAD", you: 55, target: 70 },
  { skill: "Safety", you: 80, target: 85 },
];

function Page() {
  const [step, setStep] = useState<1 | 2 | 3>(3);
  return (
    <AppShell
      nav={officerNav}
      user={officerUser}
      rightPanel={
        <AIPanel
          title="Report Explainer"
          subtitle="Ask anything about this report"
          why={<p>The L&D roadmap is generated by mapping skill demand (90-day rolling) against current TVET and HRDC course inventories. Confidence intervals shown where sample size is &gt;200.</p>}
        >
          <div className="space-y-3 text-[12px]">
            <div className="rounded-[10px] border border-border p-3">
              <div className="font-600">Top question this week</div>
              <p className="mt-1 text-muted-foreground">"Which courses bridge the PLC gap in 8 weeks?"</p>
            </div>
            <button className="inline-flex h-9 w-full items-center justify-center gap-1.5 rounded-[10px] grad-orange text-[12px] font-600 text-white">
              <Sparkles className="h-3.5 w-3.5"/> Ask a follow-up
            </button>
            <button className="inline-flex h-9 w-full items-center justify-center gap-1.5 rounded-[10px] border border-border bg-card text-[12px] font-600">
              <Download className="h-3.5 w-3.5"/> Export PDF
            </button>
          </div>
        </AIPanel>
      }
    >
      <div className="mb-6">
        <div className="text-[12px] font-600 uppercase tracking-wider text-emphasis">Research Hub</div>
        <h1 className="text-[28px] font-700 tracking-tight">Electrical & Electronics demand in Klang Valley</h1>
      </div>

      {/* Stepper */}
      <ol className="mb-6 flex gap-2">
        {["Query", "Guided Q&A", "Report"].map((s, i) => {
          const idx = (i + 1) as 1 | 2 | 3;
          const active = step === idx;
          const done = idx < step;
          return (
            <li key={s}>
              <button
                onClick={() => setStep(idx)}
                className={`inline-flex h-9 items-center gap-2 rounded-full border px-4 text-[12px] font-600 ${
                  active ? "border-primary bg-primary-soft text-primary" : done ? "border-border bg-card text-muted-foreground" : "border-border bg-card text-muted-foreground"
                }`}
              >
                <span className={`flex h-5 w-5 items-center justify-center rounded-full text-[11px] ${active ? "bg-primary text-primary-foreground" : "bg-inset"}`}>{idx}</span>
                {s}
              </button>
            </li>
          );
        })}
      </ol>

      {step === 1 && (
        <div className="rounded-[12px] border border-border bg-card p-6 shadow-card">
          <SectionTitle title="Start with a question"/>
          <textarea defaultValue="What's the current demand for Electrical & Electronics roles in Klang Valley, and what L&D pathways close the gap?" className="mt-2 h-32 w-full rounded-[10px] border border-border bg-inset p-3 text-sm outline-none focus:border-primary focus:bg-card"/>
          <button onClick={() => setStep(2)} className="mt-3 inline-flex h-10 items-center rounded-[10px] bg-primary px-4 text-sm font-600 text-primary-foreground">Continue <ArrowRight className="ml-1 h-4 w-4"/></button>
        </div>
      )}

      {step === 2 && (
        <div className="rounded-[12px] border border-border bg-card p-6 shadow-card">
          <SectionTitle title="Refine your scope" action={<Badge tone="ai"><Sparkles className="h-3 w-3"/> AI guide</Badge>}/>
          {[
            { q: "Region", chips: ["Klang Valley", "Northern", "Southern", "East coast"] },
            { q: "Time window", chips: ["Last 30 days", "Last 90 days", "YTD"] },
            { q: "Cohort", chips: ["All", "Youth 18-24", "Re-entrants", "Disability inclusion"] },
          ].map((g) => (
            <div key={g.q} className="mt-4">
              <div className="mb-2 text-[12px] font-600 text-muted-foreground">{g.q}</div>
              <div className="flex flex-wrap gap-2">{g.chips.map((c, i) => (
                <button key={c} className={`rounded-full px-3 py-1.5 text-[12px] ${i === 0 ? "bg-primary text-primary-foreground" : "border border-border bg-card"}`}>{c}</button>
              ))}</div>
            </div>
          ))}
          <textarea placeholder="Anything else to add?" className="mt-4 h-20 w-full rounded-[10px] border border-border bg-inset p-3 text-sm outline-none"/>
          <button onClick={() => setStep(3)} className="mt-3 inline-flex h-10 items-center rounded-[10px] bg-primary px-4 text-sm font-600 text-primary-foreground">Generate report <ArrowRight className="ml-1 h-4 w-4"/></button>
        </div>
      )}

      {step === 3 && (
        <div className="space-y-6">
          {/* Exec summary */}
          <section className="rounded-[12px] border border-border bg-card p-6 shadow-card">
            <SectionTitle kicker="Executive summary" title="What you need to know" action={<Badge tone="ai"><Sparkles className="h-3 w-3"/> AI</Badge>}/>
            <p className="text-[14px] leading-relaxed text-muted-foreground">
              Demand for Electrical & Electronics technicians in Klang Valley grew <b className="text-emphasis">38%</b> over 90 days, led by <b>Sungai Buloh</b> and <b>Shah Alam</b>. Supply is concentrated in fresh TVET graduates with limited <b>PLC</b> and <b>robotics</b> exposure. A 12-week intervention bundling PLC + robotics could close <b>60%</b> of the gap by Q3.
            </p>
          </section>

          {/* KPIs */}
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <KPITile label="Open vacancies (90d)" value="1,820" delta="+38% vs prev." emphasis gradient/>
            <KPITile label="Avg. salary" value="RM 4.2k" delta="Range 3.2 – 5.6k"/>
            <KPITile label="Skill-readiness gap" value="42%" delta="PLC + robotics"/>
            <KPITile label="Time to fill" value="34 days" delta="Industry avg 28"/>
          </div>

          {/* Chart */}
          <section className="rounded-[12px] border border-border bg-card p-6 shadow-card">
            <SectionTitle title="Market demand · weekly"/>
            <div className="flex h-44 items-end gap-1.5">
              {[35,40,48,42,55,52,60,72,68,80,86,92].map((v, i) => (
                <div key={i} className="flex-1 rounded-t-md" style={{ height: `${v}%`, background: i === 11 ? "var(--emphasis)" : "var(--primary)" }}/>
              ))}
            </div>
            <div className="mt-2 flex justify-between text-[10px] text-muted-foreground"><span>W1</span><span>W6</span><span>W12</span></div>
          </section>

          <div className="grid gap-6 lg:grid-cols-2">
            {/* Radar */}
            <section className="rounded-[12px] border border-border bg-card p-6 shadow-card">
              <SectionTitle title="Skill-readiness radar"/>
              <ul className="space-y-3">
                {skillsRadar.map((s) => (
                  <li key={s.skill}>
                    <div className="mb-1 flex justify-between text-[13px]"><span className="font-600">{s.skill}</span><span className="num text-muted-foreground">Current {s.you} · Target {s.target}</span></div>
                    <div className="relative h-2 overflow-hidden rounded-full bg-inset">
                      <div className="absolute inset-y-0 left-0 rounded-full bg-primary" style={{ width: `${s.you}%` }}/>
                      <div className="absolute top-1/2 h-3 w-0.5 -translate-y-1/2 bg-emphasis" style={{ left: `${s.target}%` }}/>
                    </div>
                  </li>
                ))}
              </ul>
            </section>
            {/* Sourced data */}
            <section className="rounded-[12px] border border-border bg-card p-6 shadow-card">
              <SectionTitle title="Sourced data"/>
              <table className="w-full text-[12px]">
                <thead className="text-[11px] uppercase tracking-wider text-muted-foreground"><tr><th className="py-2 text-left">Source</th><th className="text-left">Period</th><th className="text-right">Records</th></tr></thead>
                <tbody>
                  {[
                    ["MYFutureJobs portal", "Last 90d", "1,820"],
                    ["PERKESO SIP claims", "FY25", "12,408"],
                    ["TVET grad registry", "2024", "5,210"],
                    ["HRDC course catalogue", "Live", "382 courses"],
                  ].map((r) => (
                    <tr key={r[0]} className="border-t border-border"><td className="py-2.5">{r[0]}</td><td>{r[1]}</td><td className="text-right num">{r[2]}</td></tr>
                  ))}
                </tbody>
              </table>
            </section>
          </div>

          {/* L&D roadmap */}
          <section className="rounded-[12px] border border-border bg-card p-6 shadow-card">
            <SectionTitle title="L&D roadmap · 12 weeks" action={<Badge tone="emphasis">Recommended</Badge>}/>
            <div className="space-y-2">
              {[
                { w: "Wk 1-4", t: "PLC Foundations (Siemens S7)", o: "200 learners · 3 centres" },
                { w: "Wk 5-8", t: "Industrial Robotics Basics", o: "200 learners · HRDC-claimable" },
                { w: "Wk 9-12", t: "Site placement & assessment", o: "Partner: 14 verified employers" },
              ].map((p) => (
                <div key={p.w} className="grid grid-cols-[80px_1fr_auto] items-center gap-3 rounded-[10px] border border-border p-3 text-[13px]">
                  <div className="text-[12px] font-600 text-emphasis">{p.w}</div>
                  <div className="font-600">{p.t}</div>
                  <div className="text-[12px] text-muted-foreground">{p.o}</div>
                </div>
              ))}
            </div>
          </section>

          <div className="flex justify-end gap-2">
            <button className="inline-flex h-10 items-center gap-1.5 rounded-[10px] border border-border px-4 text-sm font-600"><FileText className="h-4 w-4"/> Save to library</button>
            <button className="inline-flex h-10 items-center gap-1.5 rounded-[10px] grad-orange px-4 text-sm font-600 text-white"><Download className="h-4 w-4"/> Export PDF</button>
          </div>
        </div>
      )}
    </AppShell>
  );
}
