/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as JobseekerIndexRouteImport } from './routes/jobseeker.index'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as OfficerResearchRouteImport } from './routes/officer.research'
import { Route as OfficerReportsRouteImport } from './routes/officer.reports'
import { Route as OfficerEmployersRouteImport } from './routes/officer.employers'
import { Route as OfficerCasesRouteImport } from './routes/officer.cases'
import { Route as JobseekerRewardsRouteImport } from './routes/jobseeker.rewards'
import { Route as JobseekerProfileRouteImport } from './routes/jobseeker.profile'
import { Route as JobseekerJobsRouteImport } from './routes/jobseeker.jobs'
import { Route as JobseekerEventsRouteImport } from './routes/jobseeker.events'
import { Route as JobseekerCvPositioningRouteImport } from './routes/jobseeker.cv-positioning'
import { Route as JobseekerCvEditsRouteImport } from './routes/jobseeker.cv-edits'
import { Route as JobseekerCareerSignalRouteImport } from './routes/jobseeker.career-signal'
import { Route as JobseekerApplicationsRouteImport } from './routes/jobseeker.applications'
import { Route as EmployerVacanciesRouteImport } from './routes/employer.vacancies'
import { Route as EmployerJdAnalysisRouteImport } from './routes/employer.jd-analysis'
import { Route as EmployerInterviewRouteImport } from './routes/employer.interview'
import { Route as EmployerFitMatchRouteImport } from './routes/employer.fit-match'
import { Route as EmployerCompanyRouteImport } from './routes/employer.company'
import { Route as EmployerBiasRouteImport } from './routes/employer.bias'
import { Route as CompanyCompanyIdRouteImport } from './routes/company.$companyId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerIndexRoute = JobseekerIndexRouteImport.update({
  id: '/jobseeker/',
  path: '/jobseeker/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerResearchRoute = OfficerResearchRouteImport.update({
  id: '/officer/research',
  path: '/officer/research',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerReportsRoute = OfficerReportsRouteImport.update({
  id: '/officer/reports',
  path: '/officer/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerEmployersRoute = OfficerEmployersRouteImport.update({
  id: '/officer/employers',
  path: '/officer/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerCasesRoute = OfficerCasesRouteImport.update({
  id: '/officer/cases',
  path: '/officer/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerRewardsRoute = JobseekerRewardsRouteImport.update({
  id: '/jobseeker/rewards',
  path: '/jobseeker/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerProfileRoute = JobseekerProfileRouteImport.update({
  id: '/jobseeker/profile',
  path: '/jobseeker/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerJobsRoute = JobseekerJobsRouteImport.update({
  id: '/jobseeker/jobs',
  path: '/jobseeker/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerEventsRoute = JobseekerEventsRouteImport.update({
  id: '/jobseeker/events',
  path: '/jobseeker/events',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerCvPositioningRoute = JobseekerCvPositioningRouteImport.update({
  id: '/jobseeker/cv-positioning',
  path: '/jobseeker/cv-positioning',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerCvEditsRoute = JobseekerCvEditsRouteImport.update({
  id: '/jobseeker/cv-edits',
  path: '/jobseeker/cv-edits',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerCareerSignalRoute = JobseekerCareerSignalRouteImport.update({
  id: '/jobseeker/career-signal',
  path: '/jobseeker/career-signal',
  getParentRoute: () => rootRouteImport,
} as any)
const JobseekerApplicationsRoute = JobseekerApplicationsRouteImport.update({
  id: '/jobseeker/applications',
  path: '/jobseeker/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerVacanciesRoute = EmployerVacanciesRouteImport.update({
  id: '/employer/vacancies',
  path: '/employer/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJdAnalysisRoute = EmployerJdAnalysisRouteImport.update({
  id: '/employer/jd-analysis',
  path: '/employer/jd-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerInterviewRoute = EmployerInterviewRouteImport.update({
  id: '/employer/interview',
  path: '/employer/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerFitMatchRoute = EmployerFitMatchRouteImport.update({
  id: '/employer/fit-match',
  path: '/employer/fit-match',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCompanyRoute = EmployerCompanyRouteImport.update({
  id: '/employer/company',
  path: '/employer/company',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerBiasRoute = EmployerBiasRouteImport.update({
  id: '/employer/bias',
  path: '/employer/bias',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/employer/bias': typeof EmployerBiasRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/fit-match': typeof EmployerFitMatchRoute
  '/employer/interview': typeof EmployerInterviewRoute
  '/employer/jd-analysis': typeof EmployerJdAnalysisRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/career-signal': typeof JobseekerCareerSignalRoute
  '/jobseeker/cv-edits': typeof JobseekerCvEditsRoute
  '/jobseeker/cv-positioning': typeof JobseekerCvPositioningRoute
  '/jobseeker/events': typeof JobseekerEventsRoute
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/jobseeker/rewards': typeof JobseekerRewardsRoute
  '/officer/cases': typeof OfficerCasesRoute
  '/officer/employers': typeof OfficerEmployersRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/research': typeof OfficerResearchRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobseeker/': typeof JobseekerIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/employer/bias': typeof EmployerBiasRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/fit-match': typeof EmployerFitMatchRoute
  '/employer/interview': typeof EmployerInterviewRoute
  '/employer/jd-analysis': typeof EmployerJdAnalysisRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/career-signal': typeof JobseekerCareerSignalRoute
  '/jobseeker/cv-edits': typeof JobseekerCvEditsRoute
  '/jobseeker/cv-positioning': typeof JobseekerCvPositioningRoute
  '/jobseeker/events': typeof JobseekerEventsRoute
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/jobseeker/rewards': typeof JobseekerRewardsRoute
  '/officer/cases': typeof OfficerCasesRoute
  '/officer/employers': typeof OfficerEmployersRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/research': typeof OfficerResearchRoute
  '/employer': typeof EmployerIndexRoute
  '/jobseeker': typeof JobseekerIndexRoute
  '/officer': typeof OfficerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/company/$companyId': typeof CompanyCompanyIdRoute
  '/employer/bias': typeof EmployerBiasRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/fit-match': typeof EmployerFitMatchRoute
  '/employer/interview': typeof EmployerInterviewRoute
  '/employer/jd-analysis': typeof EmployerJdAnalysisRoute
  '/employer/vacancies': typeof EmployerVacanciesRoute
  '/jobseeker/applications': typeof JobseekerApplicationsRoute
  '/jobseeker/career-signal': typeof JobseekerCareerSignalRoute
  '/jobseeker/cv-edits': typeof JobseekerCvEditsRoute
  '/jobseeker/cv-positioning': typeof JobseekerCvPositioningRoute
  '/jobseeker/events': typeof JobseekerEventsRoute
  '/jobseeker/jobs': typeof JobseekerJobsRoute
  '/jobseeker/profile': typeof JobseekerProfileRoute
  '/jobseeker/rewards': typeof JobseekerRewardsRoute
  '/officer/cases': typeof OfficerCasesRoute
  '/officer/employers': typeof OfficerEmployersRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/research': typeof OfficerResearchRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobseeker/': typeof JobseekerIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/company/$companyId'
    | '/employer/bias'
    | '/employer/company'
    | '/employer/fit-match'
    | '/employer/interview'
    | '/employer/jd-analysis'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/career-signal'
    | '/jobseeker/cv-edits'
    | '/jobseeker/cv-positioning'
    | '/jobseeker/events'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/jobseeker/rewards'
    | '/officer/cases'
    | '/officer/employers'
    | '/officer/reports'
    | '/officer/research'
    | '/employer/'
    | '/jobseeker/'
    | '/officer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/company/$companyId'
    | '/employer/bias'
    | '/employer/company'
    | '/employer/fit-match'
    | '/employer/interview'
    | '/employer/jd-analysis'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/career-signal'
    | '/jobseeker/cv-edits'
    | '/jobseeker/cv-positioning'
    | '/jobseeker/events'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/jobseeker/rewards'
    | '/officer/cases'
    | '/officer/employers'
    | '/officer/reports'
    | '/officer/research'
    | '/employer'
    | '/jobseeker'
    | '/officer'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/company/$companyId'
    | '/employer/bias'
    | '/employer/company'
    | '/employer/fit-match'
    | '/employer/interview'
    | '/employer/jd-analysis'
    | '/employer/vacancies'
    | '/jobseeker/applications'
    | '/jobseeker/career-signal'
    | '/jobseeker/cv-edits'
    | '/jobseeker/cv-positioning'
    | '/jobseeker/events'
    | '/jobseeker/jobs'
    | '/jobseeker/profile'
    | '/jobseeker/rewards'
    | '/officer/cases'
    | '/officer/employers'
    | '/officer/reports'
    | '/officer/research'
    | '/employer/'
    | '/jobseeker/'
    | '/officer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRoute
  EmployerBiasRoute: typeof EmployerBiasRoute
  EmployerCompanyRoute: typeof EmployerCompanyRoute
  EmployerFitMatchRoute: typeof EmployerFitMatchRoute
  EmployerInterviewRoute: typeof EmployerInterviewRoute
  EmployerJdAnalysisRoute: typeof EmployerJdAnalysisRoute
  EmployerVacanciesRoute: typeof EmployerVacanciesRoute
  JobseekerApplicationsRoute: typeof JobseekerApplicationsRoute
  JobseekerCareerSignalRoute: typeof JobseekerCareerSignalRoute
  JobseekerCvEditsRoute: typeof JobseekerCvEditsRoute
  JobseekerCvPositioningRoute: typeof JobseekerCvPositioningRoute
  JobseekerEventsRoute: typeof JobseekerEventsRoute
  JobseekerJobsRoute: typeof JobseekerJobsRoute
  JobseekerProfileRoute: typeof JobseekerProfileRoute
  JobseekerRewardsRoute: typeof JobseekerRewardsRoute
  OfficerCasesRoute: typeof OfficerCasesRoute
  OfficerEmployersRoute: typeof OfficerEmployersRoute
  OfficerReportsRoute: typeof OfficerReportsRoute
  OfficerResearchRoute: typeof OfficerResearchRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  JobseekerIndexRoute: typeof JobseekerIndexRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/': {
      id: '/jobseeker/'
      path: '/jobseeker'
      fullPath: '/jobseeker/'
      preLoaderRoute: typeof JobseekerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/': {
      id: '/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/research': {
      id: '/officer/research'
      path: '/officer/research'
      fullPath: '/officer/research'
      preLoaderRoute: typeof OfficerResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/reports': {
      id: '/officer/reports'
      path: '/officer/reports'
      fullPath: '/officer/reports'
      preLoaderRoute: typeof OfficerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/employers': {
      id: '/officer/employers'
      path: '/officer/employers'
      fullPath: '/officer/employers'
      preLoaderRoute: typeof OfficerEmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/cases': {
      id: '/officer/cases'
      path: '/officer/cases'
      fullPath: '/officer/cases'
      preLoaderRoute: typeof OfficerCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/rewards': {
      id: '/jobseeker/rewards'
      path: '/jobseeker/rewards'
      fullPath: '/jobseeker/rewards'
      preLoaderRoute: typeof JobseekerRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/profile': {
      id: '/jobseeker/profile'
      path: '/jobseeker/profile'
      fullPath: '/jobseeker/profile'
      preLoaderRoute: typeof JobseekerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/jobs': {
      id: '/jobseeker/jobs'
      path: '/jobseeker/jobs'
      fullPath: '/jobseeker/jobs'
      preLoaderRoute: typeof JobseekerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/events': {
      id: '/jobseeker/events'
      path: '/jobseeker/events'
      fullPath: '/jobseeker/events'
      preLoaderRoute: typeof JobseekerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/cv-positioning': {
      id: '/jobseeker/cv-positioning'
      path: '/jobseeker/cv-positioning'
      fullPath: '/jobseeker/cv-positioning'
      preLoaderRoute: typeof JobseekerCvPositioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/cv-edits': {
      id: '/jobseeker/cv-edits'
      path: '/jobseeker/cv-edits'
      fullPath: '/jobseeker/cv-edits'
      preLoaderRoute: typeof JobseekerCvEditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/career-signal': {
      id: '/jobseeker/career-signal'
      path: '/jobseeker/career-signal'
      fullPath: '/jobseeker/career-signal'
      preLoaderRoute: typeof JobseekerCareerSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobseeker/applications': {
      id: '/jobseeker/applications'
      path: '/jobseeker/applications'
      fullPath: '/jobseeker/applications'
      preLoaderRoute: typeof JobseekerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/vacancies': {
      id: '/employer/vacancies'
      path: '/employer/vacancies'
      fullPath: '/employer/vacancies'
      preLoaderRoute: typeof EmployerVacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jd-analysis': {
      id: '/employer/jd-analysis'
      path: '/employer/jd-analysis'
      fullPath: '/employer/jd-analysis'
      preLoaderRoute: typeof EmployerJdAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/interview': {
      id: '/employer/interview'
      path: '/employer/interview'
      fullPath: '/employer/interview'
      preLoaderRoute: typeof EmployerInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/fit-match': {
      id: '/employer/fit-match'
      path: '/employer/fit-match'
      fullPath: '/employer/fit-match'
      preLoaderRoute: typeof EmployerFitMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/company': {
      id: '/employer/company'
      path: '/employer/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof EmployerCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/bias': {
      id: '/employer/bias'
      path: '/employer/bias'
      fullPath: '/employer/bias'
      preLoaderRoute: typeof EmployerBiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRoute,
  EmployerBiasRoute: EmployerBiasRoute,
  EmployerCompanyRoute: EmployerCompanyRoute,
  EmployerFitMatchRoute: EmployerFitMatchRoute,
  EmployerInterviewRoute: EmployerInterviewRoute,
  EmployerJdAnalysisRoute: EmployerJdAnalysisRoute,
  EmployerVacanciesRoute: EmployerVacanciesRoute,
  JobseekerApplicationsRoute: JobseekerApplicationsRoute,
  JobseekerCareerSignalRoute: JobseekerCareerSignalRoute,
  JobseekerCvEditsRoute: JobseekerCvEditsRoute,
  JobseekerCvPositioningRoute: JobseekerCvPositioningRoute,
  JobseekerEventsRoute: JobseekerEventsRoute,
  JobseekerJobsRoute: JobseekerJobsRoute,
  JobseekerProfileRoute: JobseekerProfileRoute,
  JobseekerRewardsRoute: JobseekerRewardsRoute,
  OfficerCasesRoute: OfficerCasesRoute,
  OfficerEmployersRoute: OfficerEmployersRoute,
  OfficerReportsRoute: OfficerReportsRoute,
  OfficerResearchRoute: OfficerResearchRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  JobseekerIndexRoute: JobseekerIndexRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
